version: "3.7"
 
services:
  web:
    image: amazon_s3_manager:1.1.1
    build: .
    command: gunicorn amazon_s3_manager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/amazon_s3_manager
      - static:/static/
    expose:
      - 8000
    env_file:
    - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.dev
  nginx:
    build: ./nginx
    volumes:
      - static:/static/
    ports:
      - 81:81
    depends_on:
      - web
volumes:
  postgres_data:
  static: