# Generated by Django 4.0.1 on 2022-01-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=255, unique=True, verbose_name='Название бакета')),
                ('region_name', models.CharField(max_length=255, verbose_name='Регион')),
                ('created', models.CharField(max_length=40, verbose_name='Создан')),
                ('count', models.IntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='json_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название приложения')),
                ('content', models.JSONField(max_length=255, verbose_name='Содержимое')),
                ('last_update', models.CharField(max_length=40, verbose_name='Последнее обновление')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buckets_manager.buckets')),
            ],
        ),
    ]
