# Generated by Django 4.0.1 on 2022-01-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buckets',
            name='count',
        ),
    ]
